### ISSUE TITLE
Plz help me i tried many time still showing this

### ISSUE THREAD

**Issue by adnan9980k** [Democles01/InstaHack-Test#1]
Traceback (most recent call last):
  File "hackinsta.py", line 154, in <module>
    sess = instabrute.Login(password)
  File "hackinsta.py", line 118, in Login
    sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})
KeyError: 'csrftoken'

**Comment by sankopay** [comment]
@Democles01 @adnan9980k ProxyError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000020D19C4BCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))


MY ISSUE IS THIS ONE, SOLVE IT PLEASEEEEEEE

**Comment by liamthedux124** [comment]
@sankopay its the proxies
